<?php

return array(
  array('id' => '1','state_id' => '1','name' => 'North and Middle Andaman'),
  array('id' => '2','state_id' => '1','name' => 'South Andaman'),
  array('id' => '3','state_id' => '1','name' => 'Nicobar'),
  array('id' => '4','state_id' => '2','name' => 'Krishna'),
  array('id' => '5','state_id' => '2','name' => 'Guntur'),
  array('id' => '6','state_id' => '2','name' => 'YSR District, Kadapa (Cuddapah)'),
  array('id' => '7','state_id' => '2','name' => 'Kurnool'),
  array('id' => '8','state_id' => '2','name' => 'Visakhapatnam'),
  array('id' => '9','state_id' => '2','name' => 'Anantapur'),
  array('id' => '10','state_id' => '2','name' => 'Chittoor'),
  array('id' => '11','state_id' => '2','name' => 'East Godavari'),
  array('id' => '12','state_id' => '2','name' => 'Prakasam'),
  array('id' => '13','state_id' => '2','name' => 'Sri Potti Sriramulu Nellore'),
  array('id' => '14','state_id' => '2','name' => 'Srikakulam'),
  array('id' => '15','state_id' => '2','name' => 'Vizianagaram'),
  array('id' => '16','state_id' => '2','name' => 'West Godavari'),
  array('id' => '17','state_id' => '3','name' => 'Itanagar Capital Complex'),
  array('id' => '18','state_id' => '3','name' => 'Lower Siang'),
  array('id' => '19','state_id' => '3','name' => 'Pakke Kessang'),
  array('id' => '20','state_id' => '3','name' => 'Changlang'),
  array('id' => '21','state_id' => '3','name' => 'Kurung Kumey'),
  array('id' => '22','state_id' => '3','name' => 'Anjaw'),
  array('id' => '23','state_id' => '3','name' => 'East Kameng'),
  array('id' => '24','state_id' => '3','name' => 'Kamle'),
  array('id' => '25','state_id' => '3','name' => 'Dibang Valley'),
  array('id' => '26','state_id' => '3','name' => 'Tirap'),
  array('id' => '27','state_id' => '3','name' => 'Kra Daadi'),
  array('id' => '28','state_id' => '3','name' => 'West Kameng'),
  array('id' => '29','state_id' => '3','name' => 'Lohit'),
  array('id' => '30','state_id' => '3','name' => 'Tawang'),
  array('id' => '31','state_id' => '3','name' => 'Lower Dibang Valley'),
  array('id' => '32','state_id' => '3','name' => 'Lower Subansiri'),
  array('id' => '33','state_id' => '3','name' => 'Lepa Rada'),
  array('id' => '34','state_id' => '3','name' => 'Upper Siang'),
  array('id' => '35','state_id' => '3','name' => 'Shi Yomi'),
  array('id' => '36','state_id' => '3','name' => 'Namsai'),
  array('id' => '37','state_id' => '3','name' => 'Siang'),
  array('id' => '38','state_id' => '3','name' => 'West Siang'),
  array('id' => '39','state_id' => '3','name' => 'Papum Pare'),
  array('id' => '40','state_id' => '3','name' => 'Longding'),
  array('id' => '41','state_id' => '3','name' => 'Upper Subansiri'),
  array('id' => '42','state_id' => '3','name' => 'East Siang'),
  array('id' => '43','state_id' => '4','name' => 'Dibrugarh'),
  array('id' => '44','state_id' => '4','name' => 'Sivasagar'),
  array('id' => '45','state_id' => '4','name' => 'Tinsukia'),
  array('id' => '46','state_id' => '4','name' => 'Baksa'),
  array('id' => '47','state_id' => '4','name' => 'Barpeta'),
  array('id' => '48','state_id' => '4','name' => 'Darrang'),
  array('id' => '49','state_id' => '4','name' => 'Kamrup Metropolitan'),
  array('id' => '50','state_id' => '4','name' => 'Kamrup Rural'),
  array('id' => '51','state_id' => '4','name' => 'Karbi-Anglong'),
  array('id' => '52','state_id' => '4','name' => 'Nalbari'),
  array('id' => '53','state_id' => '4','name' => 'Golaghat'),
  array('id' => '54','state_id' => '4','name' => 'Jorhat'),
  array('id' => '55','state_id' => '4','name' => 'Morigaon'),
  array('id' => '56','state_id' => '4','name' => 'Nagaon'),
  array('id' => '57','state_id' => '4','name' => 'Bongaigaon'),
  array('id' => '58','state_id' => '4','name' => 'Chirang'),
  array('id' => '59','state_id' => '4','name' => 'Dhubri'),
  array('id' => '60','state_id' => '4','name' => 'Goalpara'),
  array('id' => '61','state_id' => '4','name' => 'Kokrajhar'),
  array('id' => '62','state_id' => '4','name' => 'Dhemaji'),
  array('id' => '63','state_id' => '4','name' => 'Lakhimpur'),
  array('id' => '64','state_id' => '4','name' => 'Sonitpur'),
  array('id' => '65','state_id' => '4','name' => 'Udalguri'),
  array('id' => '66','state_id' => '4','name' => 'Cachar'),
  array('id' => '67','state_id' => '4','name' => 'Dima Hasao'),
  array('id' => '68','state_id' => '4','name' => 'Hailakandi'),
  array('id' => '69','state_id' => '4','name' => 'Karimganj'),
  array('id' => '70','state_id' => '5','name' => 'Madhepura'),
  array('id' => '71','state_id' => '5','name' => 'Saharsa'),
  array('id' => '72','state_id' => '5','name' => 'Supaul'),
  array('id' => '73','state_id' => '5','name' => 'Purnia'),
  array('id' => '74','state_id' => '5','name' => 'Araria'),
  array('id' => '75','state_id' => '5','name' => 'Katihar'),
  array('id' => '76','state_id' => '5','name' => 'Kishanganj'),
  array('id' => '77','state_id' => '5','name' => 'Aurangabad'),
  array('id' => '78','state_id' => '5','name' => 'Arwal'),
  array('id' => '79','state_id' => '5','name' => 'Gaya'),
  array('id' => '80','state_id' => '5','name' => 'Kaimur'),
  array('id' => '81','state_id' => '5','name' => 'Rohtas'),
  array('id' => '82','state_id' => '5','name' => 'Bhagalpur'),
  array('id' => '83','state_id' => '5','name' => 'Banka'),
  array('id' => '84','state_id' => '5','name' => 'Lakhisarai'),
  array('id' => '85','state_id' => '5','name' => 'Munger'),
  array('id' => '86','state_id' => '5','name' => 'Muzaffarpur'),
  array('id' => '87','state_id' => '5','name' => 'Sheohar'),
  array('id' => '88','state_id' => '5','name' => 'Sitamarhi'),
  array('id' => '89','state_id' => '5','name' => 'Vaishali'),
  array('id' => '90','state_id' => '5','name' => 'Nalanda'),
  array('id' => '91','state_id' => '5','name' => 'Jehanabad'),
  array('id' => '92','state_id' => '5','name' => 'Nawada'),
  array('id' => '93','state_id' => '5','name' => 'Sheikhpura'),
  array('id' => '94','state_id' => '5','name' => 'Darbhanga'),
  array('id' => '95','state_id' => '5','name' => 'Madhubani'),
  array('id' => '96','state_id' => '5','name' => 'Samastipur'),
  array('id' => '97','state_id' => '5','name' => 'Patna'),
  array('id' => '98','state_id' => '5','name' => 'Begusarai'),
  array('id' => '99','state_id' => '5','name' => 'Bhojpur'),
  array('id' => '100','state_id' => '5','name' => 'Buxar'),
  array('id' => '101','state_id' => '5','name' => 'Khagaria'),
  array('id' => '102','state_id' => '5','name' => 'Saran'),
  array('id' => '103','state_id' => '5','name' => 'Siwan'),
  array('id' => '104','state_id' => '5','name' => 'Gopalganj'),
  array('id' => '105','state_id' => '5','name' => 'East Champaran'),
  array('id' => '106','state_id' => '5','name' => 'West Champaran'),
  array('id' => '107','state_id' => '5','name' => 'Jamui'),
  array('id' => '108','state_id' => '6','name' => 'Chandigarh'),
  array('id' => '109','state_id' => '7','name' => 'Raipur'),
  array('id' => '110','state_id' => '7','name' => 'Balod'),
  array('id' => '111','state_id' => '7','name' => 'Baloda bazar'),
  array('id' => '112','state_id' => '7','name' => 'Balrampur'),
  array('id' => '113','state_id' => '7','name' => 'Bastar'),
  array('id' => '114','state_id' => '7','name' => 'Bemetara'),
  array('id' => '115','state_id' => '7','name' => 'Bijapur'),
  array('id' => '116','state_id' => '7','name' => 'Bilaspur'),
  array('id' => '117','state_id' => '7','name' => 'Dantewada'),
  array('id' => '118','state_id' => '7','name' => 'Dhamtari'),
  array('id' => '119','state_id' => '7','name' => 'Durg'),
  array('id' => '120','state_id' => '7','name' => 'Gariaband'),
  array('id' => '121','state_id' => '7','name' => 'Janjgir-Champa'),
  array('id' => '122','state_id' => '7','name' => 'Jashpur'),
  array('id' => '123','state_id' => '7','name' => 'Kanker'),
  array('id' => '124','state_id' => '7','name' => 'Kondagaon'),
  array('id' => '125','state_id' => '7','name' => 'Korba'),
  array('id' => '126','state_id' => '7','name' => 'Koriya'),
  array('id' => '127','state_id' => '7','name' => 'Mahasamund'),
  array('id' => '128','state_id' => '7','name' => 'Mungeli'),
  array('id' => '129','state_id' => '7','name' => 'Narayanpur'),
  array('id' => '130','state_id' => '7','name' => 'Raigarh'),
  array('id' => '131','state_id' => '7','name' => 'Rajnandgaon'),
  array('id' => '132','state_id' => '7','name' => 'Sukma'),
  array('id' => '133','state_id' => '7','name' => 'Surajpur'),
  array('id' => '134','state_id' => '7','name' => 'Surguja'),
  array('id' => '135','state_id' => '7','name' => 'Kawardha'),
  array('id' => '136','state_id' => '7','name' => 'Gaurela Pendra Marwahi '),
  array('id' => '137','state_id' => '8','name' => 'Dadra and Nagar Haveli'),
  array('id' => '138','state_id' => '37','name' => 'Daman'),
  array('id' => '139','state_id' => '37','name' => 'Diu'),
  array('id' => '140','state_id' => '9','name' => 'New Delhi'),
  array('id' => '141','state_id' => '9','name' => 'Central Delhi'),
  array('id' => '142','state_id' => '9','name' => 'West Delhi'),
  array('id' => '143','state_id' => '9','name' => 'North West Delhi'),
  array('id' => '144','state_id' => '9','name' => 'South East Delhi'),
  array('id' => '145','state_id' => '9','name' => 'East Delhi'),
  array('id' => '146','state_id' => '9','name' => 'North Delhi'),
  array('id' => '147','state_id' => '9','name' => 'North East Delhi'),
  array('id' => '148','state_id' => '9','name' => 'Shahdara'),
  array('id' => '149','state_id' => '9','name' => 'South Delhi'),
  array('id' => '150','state_id' => '9','name' => 'South West Delhi'),
  array('id' => '151','state_id' => '10','name' => 'North Goa'),
  array('id' => '152','state_id' => '10','name' => 'South Goa'),
  array('id' => '153','state_id' => '11','name' => 'Gandhinagar'),
  array('id' => '154','state_id' => '11','name' => 'Ahmedabad'),
  array('id' => '155','state_id' => '11','name' => 'Vadodara'),
  array('id' => '156','state_id' => '11','name' => 'Kheda'),
  array('id' => '157','state_id' => '11','name' => 'Surendranagar'),
  array('id' => '158','state_id' => '11','name' => 'Aravalli'),
  array('id' => '159','state_id' => '11','name' => 'Banaskantha'),
  array('id' => '160','state_id' => '11','name' => 'Mehsana'),
  array('id' => '161','state_id' => '11','name' => 'Patan'),
  array('id' => '162','state_id' => '11','name' => 'Sabarkantha'),
  array('id' => '163','state_id' => '11','name' => 'Dang'),
  array('id' => '164','state_id' => '11','name' => 'Navsari'),
  array('id' => '165','state_id' => '11','name' => 'Surat'),
  array('id' => '166','state_id' => '11','name' => 'Tapi'),
  array('id' => '167','state_id' => '11','name' => 'Valsad'),
  array('id' => '168','state_id' => '11','name' => 'Devbhumi Dwaraka'),
  array('id' => '169','state_id' => '11','name' => 'Jamnagar'),
  array('id' => '170','state_id' => '11','name' => 'Kutch'),
  array('id' => '171','state_id' => '11','name' => 'Morbi'),
  array('id' => '172','state_id' => '11','name' => 'Porbandar'),
  array('id' => '173','state_id' => '11','name' => 'Rajkot'),
  array('id' => '174','state_id' => '11','name' => 'Amreli'),
  array('id' => '175','state_id' => '11','name' => 'Bhavnagar'),
  array('id' => '176','state_id' => '11','name' => 'Botad'),
  array('id' => '177','state_id' => '11','name' => 'Gir Somnath'),
  array('id' => '178','state_id' => '11','name' => 'Junagadh'),
  array('id' => '179','state_id' => '11','name' => 'Anand'),
  array('id' => '180','state_id' => '11','name' => 'Bharuch'),
  array('id' => '181','state_id' => '11','name' => 'Chhotaudepur'),
  array('id' => '182','state_id' => '11','name' => 'Dahod'),
  array('id' => '183','state_id' => '11','name' => 'Mahisagar'),
  array('id' => '184','state_id' => '11','name' => 'Narmada'),
  array('id' => '185','state_id' => '11','name' => 'Panchmahal'),
  array('id' => '186','state_id' => '12','name' => 'Kurukshetra'),
  array('id' => '187','state_id' => '12','name' => 'Panchkula'),
  array('id' => '188','state_id' => '12','name' => 'Gurgaon'),
  array('id' => '189','state_id' => '12','name' => 'Jhajjar'),
  array('id' => '190','state_id' => '12','name' => 'Kaithal'),
  array('id' => '191','state_id' => '12','name' => 'Hisar'),
  array('id' => '192','state_id' => '12','name' => 'Rohtak'),
  array('id' => '193','state_id' => '12','name' => 'Ambala'),
  array('id' => '194','state_id' => '12','name' => 'Sirsa'),
  array('id' => '195','state_id' => '12','name' => 'Panipat'),
  array('id' => '196','state_id' => '12','name' => 'Fatehabad'),
  array('id' => '197','state_id' => '12','name' => 'Yamunanagar'),
  array('id' => '198','state_id' => '12','name' => 'Sonipat'),
  array('id' => '199','state_id' => '12','name' => 'Faridabad'),
  array('id' => '200','state_id' => '12','name' => 'Bhiwani'),
  array('id' => '201','state_id' => '12','name' => 'Charkhi Dadri'),
  array('id' => '202','state_id' => '12','name' => 'Rewari'),
  array('id' => '203','state_id' => '12','name' => 'Karnal'),
  array('id' => '204','state_id' => '12','name' => 'Jind'),
  array('id' => '205','state_id' => '12','name' => 'Nuh'),
  array('id' => '206','state_id' => '12','name' => 'Mahendragarh'),
  array('id' => '207','state_id' => '12','name' => 'Palwal'),
  array('id' => '208','state_id' => '13','name' => 'Shimla'),
  array('id' => '209','state_id' => '13','name' => 'Solan'),
  array('id' => '210','state_id' => '13','name' => 'Lahaul Spiti'),
  array('id' => '211','state_id' => '13','name' => 'Kullu'),
  array('id' => '212','state_id' => '13','name' => 'Sirmaur'),
  array('id' => '213','state_id' => '13','name' => 'Kangra'),
  array('id' => '214','state_id' => '13','name' => 'Chamba'),
  array('id' => '215','state_id' => '13','name' => 'Mandi'),
  array('id' => '216','state_id' => '13','name' => 'Kinnaur'),
  array('id' => '217','state_id' => '13','name' => 'Hamirpur'),
  array('id' => '218','state_id' => '13','name' => 'Una'),
  array('id' => '219','state_id' => '13','name' => 'Bilaspur'),
  array('id' => '220','state_id' => '14','name' => 'Srinagar'),
  array('id' => '221','state_id' => '14','name' => 'Kulgam'),
  array('id' => '222','state_id' => '14','name' => 'Shopian'),
  array('id' => '223','state_id' => '14','name' => 'Bandipore'),
  array('id' => '224','state_id' => '14','name' => 'Anantnag'),
  array('id' => '225','state_id' => '14','name' => 'Baramulla'),
  array('id' => '226','state_id' => '14','name' => 'Kupwara'),
  array('id' => '227','state_id' => '14','name' => 'Pulwama'),
  array('id' => '228','state_id' => '14','name' => 'Ganderbal'),
  array('id' => '229','state_id' => '14','name' => 'Budgam'),
  array('id' => '230','state_id' => '14','name' => 'Jammu'),
  array('id' => '231','state_id' => '14','name' => 'Kishtwar'),
  array('id' => '232','state_id' => '14','name' => 'Doda'),
  array('id' => '233','state_id' => '14','name' => 'Udhampur'),
  array('id' => '234','state_id' => '14','name' => 'Kathua'),
  array('id' => '235','state_id' => '14','name' => 'Ramban'),
  array('id' => '236','state_id' => '14','name' => 'Samba'),
  array('id' => '237','state_id' => '14','name' => 'Rajouri'),
  array('id' => '238','state_id' => '14','name' => 'Poonch'),
  array('id' => '239','state_id' => '14','name' => 'Reasi'),
  array('id' => '240','state_id' => '15','name' => 'Ranchi'),
  array('id' => '241','state_id' => '15','name' => 'Koderma'),
  array('id' => '242','state_id' => '15','name' => 'Bokaro'),
  array('id' => '243','state_id' => '15','name' => 'Garhwa'),
  array('id' => '244','state_id' => '15','name' => 'Latehar'),
  array('id' => '245','state_id' => '15','name' => 'Chatra'),
  array('id' => '246','state_id' => '15','name' => 'Palamu'),
  array('id' => '247','state_id' => '15','name' => 'East Singhbhum'),
  array('id' => '248','state_id' => '15','name' => 'Seraikela Kharsawan'),
  array('id' => '249','state_id' => '15','name' => 'Simdega'),
  array('id' => '250','state_id' => '15','name' => 'Lohardaga'),
  array('id' => '251','state_id' => '15','name' => 'Gumla'),
  array('id' => '252','state_id' => '15','name' => 'Khunti'),
  array('id' => '253','state_id' => '15','name' => 'Deoghar'),
  array('id' => '254','state_id' => '15','name' => 'Ramgarh'),
  array('id' => '255','state_id' => '15','name' => 'Hazaribagh'),
  array('id' => '256','state_id' => '15','name' => 'Giridih'),
  array('id' => '257','state_id' => '15','name' => 'Dhanbad'),
  array('id' => '258','state_id' => '15','name' => 'Dumka'),
  array('id' => '259','state_id' => '15','name' => 'Jamtara'),
  array('id' => '260','state_id' => '15','name' => 'Sahebganj'),
  array('id' => '261','state_id' => '15','name' => 'Pakur'),
  array('id' => '262','state_id' => '15','name' => 'Godda'),
  array('id' => '263','state_id' => '15','name' => 'West Singhbhum'),
  array('id' => '264','state_id' => '16','name' => 'Belgaum'),
  array('id' => '265','state_id' => '16','name' => 'Bangalore Urban'),
  array('id' => '266','state_id' => '16','name' => 'Mysore'),
  array('id' => '267','state_id' => '16','name' => 'Gulbarga'),
  array('id' => '268','state_id' => '16','name' => 'Chitradurga'),
  array('id' => '269','state_id' => '16','name' => 'Dakshina Kannada'),
  array('id' => '270','state_id' => '16','name' => 'Bagalkot'),
  array('id' => '271','state_id' => '16','name' => 'Chamarajanagar'),
  array('id' => '272','state_id' => '16','name' => 'Bidar'),
  array('id' => '273','state_id' => '16','name' => 'Chikamagalur'),
  array('id' => '274','state_id' => '16','name' => 'Bellary'),
  array('id' => '275','state_id' => '16','name' => 'Davanagere'),
  array('id' => '276','state_id' => '16','name' => 'Bangalore Rural'),
  array('id' => '277','state_id' => '16','name' => 'Kolar'),
  array('id' => '278','state_id' => '16','name' => 'Dharwad'),
  array('id' => '279','state_id' => '16','name' => 'Haveri'),
  array('id' => '280','state_id' => '16','name' => 'Gadag'),
  array('id' => '281','state_id' => '16','name' => 'Uttar Kannada'),
  array('id' => '282','state_id' => '16','name' => 'Koppal'),
  array('id' => '283','state_id' => '16','name' => 'Kodagu'),
  array('id' => '284','state_id' => '16','name' => 'Raichur'),
  array('id' => '285','state_id' => '16','name' => 'Yadgir'),
  array('id' => '286','state_id' => '16','name' => 'Udupi'),
  array('id' => '287','state_id' => '16','name' => 'Shimoga'),
  array('id' => '288','state_id' => '16','name' => 'Tumkur'),
  array('id' => '289','state_id' => '16','name' => 'Hassan'),
  array('id' => '290','state_id' => '16','name' => 'Mandya'),
  array('id' => '291','state_id' => '16','name' => 'Chikkaballapur'),
  array('id' => '292','state_id' => '16','name' => 'Ramanagara'),
  array('id' => '293','state_id' => '16','name' => 'Vijayapura'),
  array('id' => '294','state_id' => '16','name' => 'BBMP'),
  array('id' => '295','state_id' => '17','name' => 'Kasaragod'),
  array('id' => '296','state_id' => '17','name' => 'Thiruvananthapuram'),
  array('id' => '297','state_id' => '17','name' => 'Kannur'),
  array('id' => '298','state_id' => '17','name' => 'Kollam'),
  array('id' => '299','state_id' => '17','name' => 'Wayanad'),
  array('id' => '300','state_id' => '17','name' => 'Pathanamthitta'),
  array('id' => '301','state_id' => '17','name' => 'Alappuzha'),
  array('id' => '302','state_id' => '17','name' => 'Malappuram'),
  array('id' => '303','state_id' => '17','name' => 'Thrissur'),
  array('id' => '304','state_id' => '17','name' => 'Kottayam'),
  array('id' => '305','state_id' => '17','name' => 'Kozhikode'),
  array('id' => '306','state_id' => '17','name' => 'Idukki'),
  array('id' => '307','state_id' => '17','name' => 'Ernakulam'),
  array('id' => '308','state_id' => '17','name' => 'Palakkad'),
  array('id' => '309','state_id' => '18','name' => 'Kargil'),
  array('id' => '310','state_id' => '18','name' => 'Leh'),
  array('id' => '311','state_id' => '19','name' => 'Lakshadweep'),
  array('id' => '312','state_id' => '20','name' => 'Bhopal'),
  array('id' => '313','state_id' => '20','name' => 'Gwalior'),
  array('id' => '314','state_id' => '20','name' => 'Indore'),
  array('id' => '315','state_id' => '20','name' => 'Jabalpur'),
  array('id' => '316','state_id' => '20','name' => 'Rewa'),
  array('id' => '317','state_id' => '20','name' => 'Sagar'),
  array('id' => '318','state_id' => '20','name' => 'Ujjain'),
  array('id' => '319','state_id' => '20','name' => 'Mandsaur'),
  array('id' => '320','state_id' => '20','name' => 'Agar'),
  array('id' => '321','state_id' => '20','name' => 'Shajapur'),
  array('id' => '322','state_id' => '20','name' => 'Ratlam'),
  array('id' => '323','state_id' => '20','name' => 'Neemuch'),
  array('id' => '324','state_id' => '20','name' => 'Dewas'),
  array('id' => '325','state_id' => '20','name' => 'Tikamgarh'),
  array('id' => '326','state_id' => '20','name' => 'Panna'),
  array('id' => '327','state_id' => '20','name' => 'Damoh'),
  array('id' => '328','state_id' => '20','name' => 'Chhatarpur'),
  array('id' => '329','state_id' => '20','name' => 'Umaria'),
  array('id' => '330','state_id' => '20','name' => 'Singrauli'),
  array('id' => '331','state_id' => '20','name' => 'Sidhi'),
  array('id' => '332','state_id' => '20','name' => 'Shahdol'),
  array('id' => '333','state_id' => '20','name' => 'Satna'),
  array('id' => '334','state_id' => '20','name' => 'Anuppur'),
  array('id' => '335','state_id' => '20','name' => 'Mandla'),
  array('id' => '336','state_id' => '20','name' => 'Dindori'),
  array('id' => '337','state_id' => '20','name' => 'Chhindwara'),
  array('id' => '338','state_id' => '20','name' => 'Balaghat'),
  array('id' => '339','state_id' => '20','name' => 'Khandwa'),
  array('id' => '340','state_id' => '20','name' => 'Jhabua'),
  array('id' => '341','state_id' => '20','name' => 'Dhar'),
  array('id' => '342','state_id' => '20','name' => 'Burhanpur'),
  array('id' => '343','state_id' => '20','name' => 'Barwani'),
  array('id' => '344','state_id' => '20','name' => 'Khargone'),
  array('id' => '345','state_id' => '20','name' => 'Shivpuri'),
  array('id' => '346','state_id' => '20','name' => 'Sheopur'),
  array('id' => '347','state_id' => '20','name' => 'Morena'),
  array('id' => '348','state_id' => '20','name' => 'Guna'),
  array('id' => '349','state_id' => '20','name' => 'Seoni'),
  array('id' => '350','state_id' => '20','name' => 'Datia'),
  array('id' => '351','state_id' => '20','name' => 'Bhind'),
  array('id' => '352','state_id' => '20','name' => 'Narsinghpur'),
  array('id' => '353','state_id' => '20','name' => 'Katni'),
  array('id' => '354','state_id' => '20','name' => 'Ashoknagar'),
  array('id' => '355','state_id' => '20','name' => 'Vidisha'),
  array('id' => '356','state_id' => '20','name' => 'Sehore'),
  array('id' => '357','state_id' => '20','name' => 'Alirajpur'),
  array('id' => '358','state_id' => '20','name' => 'Rajgarh'),
  array('id' => '359','state_id' => '20','name' => 'Raisen'),
  array('id' => '360','state_id' => '20','name' => 'Hoshangabad'),
  array('id' => '361','state_id' => '20','name' => 'Harda'),
  array('id' => '362','state_id' => '20','name' => 'Betul'),
  array('id' => '363','state_id' => '21','name' => 'Pune'),
  array('id' => '364','state_id' => '21','name' => 'Akola'),
  array('id' => '365','state_id' => '21','name' => 'Nagpur'),
  array('id' => '366','state_id' => '21','name' => 'Amravati'),
  array('id' => '367','state_id' => '21','name' => 'Buldhana'),
  array('id' => '368','state_id' => '21','name' => 'Yavatmal'),
  array('id' => '369','state_id' => '21','name' => 'Washim'),
  array('id' => '370','state_id' => '21','name' => 'Bhandara'),
  array('id' => '371','state_id' => '21','name' => 'Kolhapur'),
  array('id' => '372','state_id' => '21','name' => 'Ratnagiri'),
  array('id' => '373','state_id' => '21','name' => 'Sangli'),
  array('id' => '374','state_id' => '21','name' => 'Sindhudurg'),
  array('id' => '375','state_id' => '21','name' => 'Solapur'),
  array('id' => '376','state_id' => '21','name' => 'Satara'),
  array('id' => '377','state_id' => '21','name' => 'Wardha'),
  array('id' => '378','state_id' => '21','name' => 'Gondia'),
  array('id' => '379','state_id' => '21','name' => 'Gadchiroli'),
  array('id' => '380','state_id' => '21','name' => 'Chandrapur'),
  array('id' => '381','state_id' => '21','name' => 'Osmanabad'),
  array('id' => '382','state_id' => '21','name' => 'Nanded'),
  array('id' => '383','state_id' => '21','name' => 'Latur'),
  array('id' => '384','state_id' => '21','name' => 'Beed'),
  array('id' => '385','state_id' => '21','name' => 'Parbhani'),
  array('id' => '386','state_id' => '21','name' => 'Hingoli'),
  array('id' => '387','state_id' => '21','name' => 'Nandurbar'),
  array('id' => '388','state_id' => '21','name' => 'Dhule'),
  array('id' => '389','state_id' => '21','name' => 'Nashik'),
  array('id' => '390','state_id' => '21','name' => 'Jalgaon'),
  array('id' => '391','state_id' => '21','name' => 'Ahmednagar'),
  array('id' => '392','state_id' => '21','name' => 'Thane'),
  array('id' => '393','state_id' => '21','name' => 'Raigad'),
  array('id' => '394','state_id' => '21','name' => 'Palghar'),
  array('id' => '395','state_id' => '21','name' => 'Mumbai'),
  array('id' => '396','state_id' => '21','name' => 'Jalna'),
  array('id' => '397','state_id' => '21','name' => 'Aurangabad '),
  array('id' => '398','state_id' => '22','name' => 'Bishnupur'),
  array('id' => '399','state_id' => '22','name' => 'Chandel'),
  array('id' => '400','state_id' => '22','name' => 'Churachandpur'),
  array('id' => '401','state_id' => '22','name' => 'Imphal East'),
  array('id' => '402','state_id' => '22','name' => 'Imphal West'),
  array('id' => '403','state_id' => '22','name' => 'Senapati'),
  array('id' => '404','state_id' => '22','name' => 'Tamenglong'),
  array('id' => '405','state_id' => '22','name' => 'Thoubal'),
  array('id' => '406','state_id' => '22','name' => 'Ukhrul'),
  array('id' => '407','state_id' => '22','name' => 'Tengnoupal'),
  array('id' => '408','state_id' => '22','name' => 'Kangpokpi'),
  array('id' => '409','state_id' => '22','name' => 'Kamjong'),
  array('id' => '410','state_id' => '22','name' => 'Jiribam'),
  array('id' => '411','state_id' => '22','name' => 'Pherzawl'),
  array('id' => '412','state_id' => '22','name' => 'Noney'),
  array('id' => '413','state_id' => '22','name' => 'Kakching'),
  array('id' => '414','state_id' => '23','name' => 'East Khasi Hills'),
  array('id' => '415','state_id' => '23','name' => 'South West Khasi Hills'),
  array('id' => '416','state_id' => '23','name' => 'West Jaintia Hills'),
  array('id' => '417','state_id' => '23','name' => 'Ri-Bhoi'),
  array('id' => '418','state_id' => '23','name' => 'East Jaintia Hills'),
  array('id' => '419','state_id' => '23','name' => 'West Khasi Hills'),
  array('id' => '420','state_id' => '23','name' => 'West Garo Hills'),
  array('id' => '421','state_id' => '23','name' => 'South Garo Hills'),
  array('id' => '422','state_id' => '23','name' => 'South West Garo Hills'),
  array('id' => '423','state_id' => '23','name' => 'North Garo Hills'),
  array('id' => '424','state_id' => '23','name' => 'East Garo Hills'),
  array('id' => '425','state_id' => '24','name' => 'Aizawl East'),
  array('id' => '426','state_id' => '24','name' => 'Aizawl West'),
  array('id' => '427','state_id' => '24','name' => 'Mamit'),
  array('id' => '428','state_id' => '24','name' => 'Kolasib'),
  array('id' => '429','state_id' => '24','name' => 'Champhai'),
  array('id' => '430','state_id' => '24','name' => 'Serchhip'),
  array('id' => '431','state_id' => '24','name' => 'Lunglei'),
  array('id' => '432','state_id' => '24','name' => 'Lawngtlai'),
  array('id' => '433','state_id' => '24','name' => 'Siaha'),
  array('id' => '434','state_id' => '25','name' => 'Dimapur'),
  array('id' => '435','state_id' => '25','name' => 'Peren'),
  array('id' => '436','state_id' => '25','name' => 'Wokha'),
  array('id' => '437','state_id' => '25','name' => 'Mokokchung'),
  array('id' => '438','state_id' => '25','name' => 'Longleng'),
  array('id' => '439','state_id' => '25','name' => 'Mon'),
  array('id' => '440','state_id' => '25','name' => 'Tuensang'),
  array('id' => '441','state_id' => '25','name' => 'Kohima'),
  array('id' => '442','state_id' => '25','name' => 'Zunheboto'),
  array('id' => '443','state_id' => '25','name' => 'Phek'),
  array('id' => '444','state_id' => '25','name' => 'Kiphire'),
  array('id' => '445','state_id' => '26','name' => 'Angul'),
  array('id' => '446','state_id' => '26','name' => 'Khurda'),
  array('id' => '447','state_id' => '26','name' => 'Balasore'),
  array('id' => '448','state_id' => '26','name' => 'Balangir'),
  array('id' => '449','state_id' => '26','name' => 'Ganjam'),
  array('id' => '450','state_id' => '26','name' => 'Kandhamal'),
  array('id' => '451','state_id' => '26','name' => 'Koraput'),
  array('id' => '452','state_id' => '26','name' => 'Sambalpur'),
  array('id' => '453','state_id' => '26','name' => 'Sundargarh'),
  array('id' => '454','state_id' => '26','name' => 'Bhadrak'),
  array('id' => '455','state_id' => '26','name' => 'Kendujhar'),
  array('id' => '456','state_id' => '26','name' => 'Mayurbhanj'),
  array('id' => '457','state_id' => '26','name' => 'Cuttack'),
  array('id' => '458','state_id' => '26','name' => 'Dhenkanal'),
  array('id' => '459','state_id' => '26','name' => 'Jagatsinghpur'),
  array('id' => '460','state_id' => '26','name' => 'Jajpur'),
  array('id' => '461','state_id' => '26','name' => 'Kendrapara'),
  array('id' => '462','state_id' => '26','name' => 'Nayagarh'),
  array('id' => '463','state_id' => '26','name' => 'Puri'),
  array('id' => '464','state_id' => '26','name' => 'Kalahandi'),
  array('id' => '465','state_id' => '26','name' => 'Nuapada'),
  array('id' => '466','state_id' => '26','name' => 'Subarnapur'),
  array('id' => '467','state_id' => '26','name' => 'Gajapati'),
  array('id' => '468','state_id' => '26','name' => 'Boudh'),
  array('id' => '469','state_id' => '26','name' => 'Malkangiri'),
  array('id' => '470','state_id' => '26','name' => 'Nabarangpur'),
  array('id' => '471','state_id' => '26','name' => 'Rayagada'),
  array('id' => '472','state_id' => '26','name' => 'Bargarh'),
  array('id' => '473','state_id' => '26','name' => 'Deogarh'),
  array('id' => '474','state_id' => '26','name' => 'Jharsuguda'),
  array('id' => '475','state_id' => '27','name' => 'Puducherry'),
  array('id' => '476','state_id' => '27','name' => 'Karaikal'),
  array('id' => '477','state_id' => '27','name' => 'Mahe'),
  array('id' => '478','state_id' => '27','name' => 'Yanam'),
  array('id' => '479','state_id' => '28','name' => 'Kapurthala'),
  array('id' => '480','state_id' => '28','name' => 'Ferozpur'),
  array('id' => '481','state_id' => '28','name' => 'Hoshiarpur'),
  array('id' => '482','state_id' => '28','name' => 'Mansa'),
  array('id' => '483','state_id' => '28','name' => 'Barnala'),
  array('id' => '484','state_id' => '28','name' => 'Fatehgarh Sahib'),
  array('id' => '485','state_id' => '28','name' => 'Amritsar'),
  array('id' => '486','state_id' => '28','name' => 'Pathankot'),
  array('id' => '487','state_id' => '28','name' => 'Fazilka'),
  array('id' => '488','state_id' => '28','name' => 'Ludhiana'),
  array('id' => '489','state_id' => '28','name' => 'Gurdaspur'),
  array('id' => '490','state_id' => '28','name' => 'Sri Muktsar Sahib'),
  array('id' => '491','state_id' => '28','name' => 'Moga'),
  array('id' => '492','state_id' => '28','name' => 'Jalandhar'),
  array('id' => '493','state_id' => '28','name' => 'Bathinda'),
  array('id' => '494','state_id' => '28','name' => 'Patiala'),
  array('id' => '495','state_id' => '28','name' => 'Tarn Taran'),
  array('id' => '496','state_id' => '28','name' => 'SAS Nagar'),
  array('id' => '497','state_id' => '28','name' => 'Rup Nagar'),
  array('id' => '498','state_id' => '28','name' => 'Sangrur'),
  array('id' => '499','state_id' => '28','name' => 'Faridkot'),
  array('id' => '500','state_id' => '28','name' => 'SBS Nagar'),
  array('id' => '501','state_id' => '29','name' => 'Bikaner'),
  array('id' => '502','state_id' => '29','name' => 'Jodhpur'),
  array('id' => '503','state_id' => '29','name' => 'Kota'),
  array('id' => '504','state_id' => '29','name' => 'Udaipur'),
  array('id' => '505','state_id' => '29','name' => 'Jaipur I'),
  array('id' => '506','state_id' => '29','name' => 'Jaipur II'),
  array('id' => '507','state_id' => '29','name' => 'Ajmer'),
  array('id' => '508','state_id' => '29','name' => 'Bharatpur'),
  array('id' => '509','state_id' => '29','name' => 'Sri Ganganagar'),
  array('id' => '510','state_id' => '29','name' => 'Jhunjhunu'),
  array('id' => '511','state_id' => '29','name' => 'Dausa'),
  array('id' => '512','state_id' => '29','name' => 'Alwar'),
  array('id' => '513','state_id' => '29','name' => 'Sikar'),
  array('id' => '514','state_id' => '29','name' => 'Bundi'),
  array('id' => '515','state_id' => '29','name' => 'Jhalawar'),
  array('id' => '516','state_id' => '29','name' => 'Baran'),
  array('id' => '517','state_id' => '29','name' => 'Hanumangarh'),
  array('id' => '518','state_id' => '29','name' => 'Rajsamand'),
  array('id' => '519','state_id' => '29','name' => 'Banswara'),
  array('id' => '520','state_id' => '29','name' => 'Dungarpur'),
  array('id' => '521','state_id' => '29','name' => 'Chittorgarh'),
  array('id' => '522','state_id' => '29','name' => 'Pratapgarh'),
  array('id' => '523','state_id' => '29','name' => 'Bhilwara'),
  array('id' => '524','state_id' => '29','name' => 'Dholpur'),
  array('id' => '525','state_id' => '29','name' => 'Karauli'),
  array('id' => '526','state_id' => '29','name' => 'Tonk'),
  array('id' => '527','state_id' => '29','name' => 'Jaisalmer'),
  array('id' => '528','state_id' => '29','name' => 'Barmer'),
  array('id' => '529','state_id' => '29','name' => 'Pali'),
  array('id' => '530','state_id' => '29','name' => 'Churu'),
  array('id' => '531','state_id' => '29','name' => 'Sirohi'),
  array('id' => '532','state_id' => '29','name' => 'Nagaur'),
  array('id' => '533','state_id' => '29','name' => 'Jalore'),
  array('id' => '534','state_id' => '29','name' => 'Sawai Madhopur'),
  array('id' => '535','state_id' => '30','name' => 'East Sikkim'),
  array('id' => '536','state_id' => '30','name' => 'West Sikkim'),
  array('id' => '537','state_id' => '30','name' => 'North Sikkim'),
  array('id' => '538','state_id' => '30','name' => 'South Sikkim'),
  array('id' => '539','state_id' => '31','name' => 'Coimbatore'),
  array('id' => '540','state_id' => '31','name' => 'Madurai'),
  array('id' => '541','state_id' => '31','name' => 'Thanjavur'),
  array('id' => '542','state_id' => '31','name' => 'Viluppuram'),
  array('id' => '543','state_id' => '31','name' => 'Vellore'),
  array('id' => '544','state_id' => '31','name' => 'Kanyakumari'),
  array('id' => '545','state_id' => '31','name' => 'Salem'),
  array('id' => '546','state_id' => '31','name' => 'Pudukkottai'),
  array('id' => '547','state_id' => '31','name' => 'Cuddalore'),
  array('id' => '548','state_id' => '31','name' => 'Tirunelveli'),
  array('id' => '549','state_id' => '31','name' => 'Virudhunagar'),
  array('id' => '550','state_id' => '31','name' => 'Tirupattur'),
  array('id' => '551','state_id' => '31','name' => 'Tenkasi'),
  array('id' => '552','state_id' => '31','name' => 'Kallakurichi'),
  array('id' => '553','state_id' => '31','name' => 'Tiruvannamalai'),
  array('id' => '554','state_id' => '31','name' => 'Thoothukudi (Tuticorin)'),
  array('id' => '555','state_id' => '31','name' => 'Ariyalur'),
  array('id' => '556','state_id' => '31','name' => 'Dindigul'),
  array('id' => '557','state_id' => '31','name' => 'Kanchipuram'),
  array('id' => '558','state_id' => '31','name' => 'Namakkal'),
  array('id' => '559','state_id' => '31','name' => 'Karur'),
  array('id' => '560','state_id' => '31','name' => 'Tiruchirappalli'),
  array('id' => '561','state_id' => '31','name' => 'Sivaganga'),
  array('id' => '562','state_id' => '31','name' => 'Krishnagiri'),
  array('id' => '563','state_id' => '31','name' => 'Erode'),
  array('id' => '564','state_id' => '31','name' => 'Palani'),
  array('id' => '565','state_id' => '31','name' => 'Chengalpet'),
  array('id' => '566','state_id' => '31','name' => 'Dharmapuri'),
  array('id' => '567','state_id' => '31','name' => 'Ramanathapuram'),
  array('id' => '568','state_id' => '31','name' => 'Tiruppur'),
  array('id' => '569','state_id' => '31','name' => 'Theni'),
  array('id' => '570','state_id' => '31','name' => 'Perambalur'),
  array('id' => '571','state_id' => '31','name' => 'Chennai'),
  array('id' => '572','state_id' => '31','name' => 'Tiruvallur'),
  array('id' => '573','state_id' => '31','name' => 'Paramakudi'),
  array('id' => '574','state_id' => '31','name' => 'Tiruvarur'),
  array('id' => '575','state_id' => '31','name' => 'Poonamallee'),
  array('id' => '576','state_id' => '31','name' => 'Nagapattinam'),
  array('id' => '577','state_id' => '31','name' => 'Nilgiris'),
  array('id' => '578','state_id' => '31','name' => 'Attur'),
  array('id' => '580','state_id' => '31','name' => 'Sivakasi'),
  array('id' => '581','state_id' => '32','name' => 'Hyderabad'),
  array('id' => '582','state_id' => '32','name' => 'Adilabad'),
  array('id' => '583','state_id' => '32','name' => 'Bhadradri Kothagudem'),
  array('id' => '584','state_id' => '32','name' => 'Jagtial'),
  array('id' => '585','state_id' => '32','name' => 'Jangaon'),
  array('id' => '586','state_id' => '32','name' => 'Jayashankar Bhupalpally'),
  array('id' => '587','state_id' => '32','name' => 'Jogulamba Gadwal'),
  array('id' => '588','state_id' => '32','name' => 'Kamareddy'),
  array('id' => '589','state_id' => '32','name' => 'Karimnagar'),
  array('id' => '590','state_id' => '32','name' => 'Khammam'),
  array('id' => '591','state_id' => '32','name' => 'Kumuram Bheem'),
  array('id' => '592','state_id' => '32','name' => 'Mahabubabad'),
  array('id' => '593','state_id' => '32','name' => 'Mahabubnagar'),
  array('id' => '594','state_id' => '32','name' => 'Mancherial'),
  array('id' => '595','state_id' => '32','name' => 'Medak'),
  array('id' => '596','state_id' => '32','name' => 'Medchal'),
  array('id' => '597','state_id' => '32','name' => 'Nagarkurnool'),
  array('id' => '598','state_id' => '32','name' => 'Nalgonda'),
  array('id' => '599','state_id' => '32','name' => 'Nirmal'),
  array('id' => '600','state_id' => '32','name' => 'Nizamabad'),
  array('id' => '601','state_id' => '32','name' => 'Peddapalli'),
  array('id' => '602','state_id' => '32','name' => 'Rajanna Sircilla'),
  array('id' => '603','state_id' => '32','name' => 'Rangareddy'),
  array('id' => '604','state_id' => '32','name' => 'Sangareddy'),
  array('id' => '605','state_id' => '32','name' => 'Siddipet'),
  array('id' => '606','state_id' => '32','name' => 'Suryapet'),
  array('id' => '607','state_id' => '32','name' => 'Vikarabad'),
  array('id' => '608','state_id' => '32','name' => 'Wanaparthy'),
  array('id' => '609','state_id' => '32','name' => 'Warangal(Rural)'),
  array('id' => '610','state_id' => '32','name' => 'Warangal(Urban)'),
  array('id' => '611','state_id' => '32','name' => 'Yadadri Bhuvanagiri'),
  array('id' => '612','state_id' => '32','name' => 'Mulugu'),
  array('id' => '613','state_id' => '32','name' => 'Narayanpet'),
  array('id' => '614','state_id' => '33','name' => 'Dhalai'),
  array('id' => '615','state_id' => '33','name' => 'Gomati'),
  array('id' => '616','state_id' => '33','name' => 'Khowai'),
  array('id' => '617','state_id' => '33','name' => 'North Tripura'),
  array('id' => '618','state_id' => '33','name' => 'Sepahijala'),
  array('id' => '619','state_id' => '33','name' => 'South Tripura'),
  array('id' => '620','state_id' => '33','name' => 'Unakoti'),
  array('id' => '621','state_id' => '33','name' => 'West Tripura'),
  array('id' => '622','state_id' => '34','name' => 'Agra'),
  array('id' => '623','state_id' => '34','name' => 'Aligarh'),
  array('id' => '624','state_id' => '34','name' => 'Prayagraj'),
  array('id' => '625','state_id' => '34','name' => 'Ambedkar Nagar'),
  array('id' => '626','state_id' => '34','name' => 'Amethi'),
  array('id' => '627','state_id' => '34','name' => 'Amroha'),
  array('id' => '628','state_id' => '34','name' => 'Auraiya'),
  array('id' => '629','state_id' => '34','name' => 'Azamgarh'),
  array('id' => '630','state_id' => '34','name' => 'Badaun'),
  array('id' => '631','state_id' => '34','name' => 'Baghpat'),
  array('id' => '632','state_id' => '34','name' => 'Bahraich'),
  array('id' => '633','state_id' => '34','name' => 'Balarampur'),
  array('id' => '634','state_id' => '34','name' => 'Ballia'),
  array('id' => '635','state_id' => '34','name' => 'Banda'),
  array('id' => '636','state_id' => '34','name' => 'Barabanki'),
  array('id' => '637','state_id' => '34','name' => 'Bareilly'),
  array('id' => '638','state_id' => '34','name' => 'Basti'),
  array('id' => '639','state_id' => '34','name' => 'Bijnour'),
  array('id' => '640','state_id' => '34','name' => 'Bulandshahr'),
  array('id' => '641','state_id' => '34','name' => 'Chandauli'),
  array('id' => '642','state_id' => '34','name' => 'Chitrakoot'),
  array('id' => '643','state_id' => '34','name' => 'Deoria'),
  array('id' => '644','state_id' => '34','name' => 'Etah'),
  array('id' => '645','state_id' => '34','name' => 'Etawah'),
  array('id' => '646','state_id' => '34','name' => 'Ayodhya'),
  array('id' => '647','state_id' => '34','name' => 'Farrukhabad'),
  array('id' => '648','state_id' => '34','name' => 'Fatehpur'),
  array('id' => '649','state_id' => '34','name' => 'Firozabad'),
  array('id' => '650','state_id' => '34','name' => 'Gautam Buddha Nagar'),
  array('id' => '651','state_id' => '34','name' => 'Ghaziabad'),
  array('id' => '652','state_id' => '34','name' => 'Ghazipur'),
  array('id' => '653','state_id' => '34','name' => 'Gonda'),
  array('id' => '654','state_id' => '34','name' => 'Gorakhpur'),
  array('id' => '655','state_id' => '34','name' => 'Hamirpur'),
  array('id' => '656','state_id' => '34','name' => 'Hapur'),
  array('id' => '657','state_id' => '34','name' => 'Hardoi'),
  array('id' => '658','state_id' => '34','name' => 'Hathras'),
  array('id' => '659','state_id' => '34','name' => 'Jalaun'),
  array('id' => '660','state_id' => '34','name' => 'Jaunpur'),
  array('id' => '661','state_id' => '34','name' => 'Jhansi'),
  array('id' => '662','state_id' => '34','name' => 'Kannauj'),
  array('id' => '663','state_id' => '34','name' => 'Kanpur Dehat'),
  array('id' => '664','state_id' => '34','name' => 'Kanpur Nagar'),
  array('id' => '665','state_id' => '34','name' => 'Kasganj'),
  array('id' => '666','state_id' => '34','name' => 'Kaushambi'),
  array('id' => '667','state_id' => '34','name' => 'Kushinagar'),
  array('id' => '668','state_id' => '34','name' => 'Lakhimpur Kheri'),
  array('id' => '669','state_id' => '34','name' => 'Lalitpur'),
  array('id' => '670','state_id' => '34','name' => 'Lucknow'),
  array('id' => '671','state_id' => '34','name' => 'Maharajganj'),
  array('id' => '672','state_id' => '34','name' => 'Mahoba'),
  array('id' => '673','state_id' => '34','name' => 'Mainpuri'),
  array('id' => '674','state_id' => '34','name' => 'Mathura'),
  array('id' => '675','state_id' => '34','name' => 'Mau'),
  array('id' => '676','state_id' => '34','name' => 'Meerut'),
  array('id' => '677','state_id' => '34','name' => 'Mirzapur'),
  array('id' => '678','state_id' => '34','name' => 'Moradabad'),
  array('id' => '679','state_id' => '34','name' => 'Muzaffarnagar'),
  array('id' => '680','state_id' => '34','name' => 'Pilibhit'),
  array('id' => '681','state_id' => '34','name' => 'Raebareli'),
  array('id' => '682','state_id' => '34','name' => 'Pratapgarh'),
  array('id' => '683','state_id' => '34','name' => 'Rampur'),
  array('id' => '684','state_id' => '34','name' => 'Saharanpur'),
  array('id' => '685','state_id' => '34','name' => 'Sambhal'),
  array('id' => '686','state_id' => '34','name' => 'Sant Kabir Nagar'),
  array('id' => '687','state_id' => '34','name' => 'Bhadohi'),
  array('id' => '688','state_id' => '34','name' => 'Shahjahanpur'),
  array('id' => '689','state_id' => '34','name' => 'Shamli'),
  array('id' => '690','state_id' => '34','name' => 'Shravasti'),
  array('id' => '691','state_id' => '34','name' => 'Siddharthnagar'),
  array('id' => '692','state_id' => '34','name' => 'Sitapur'),
  array('id' => '693','state_id' => '34','name' => 'Sonbhadra'),
  array('id' => '694','state_id' => '34','name' => 'Sultanpur'),
  array('id' => '695','state_id' => '34','name' => 'Unnao'),
  array('id' => '696','state_id' => '34','name' => 'Varanasi'),
  array('id' => '697','state_id' => '35','name' => 'Dehradun'),
  array('id' => '698','state_id' => '35','name' => 'Pauri Garhwal'),
  array('id' => '699','state_id' => '35','name' => 'Chamoli'),
  array('id' => '700','state_id' => '35','name' => 'Rudraprayag'),
  array('id' => '701','state_id' => '35','name' => 'Tehri Garhwal'),
  array('id' => '702','state_id' => '35','name' => 'Haridwar'),
  array('id' => '703','state_id' => '35','name' => 'Uttarkashi'),
  array('id' => '704','state_id' => '35','name' => 'Almora'),
  array('id' => '705','state_id' => '35','name' => 'Udham Singh Nagar'),
  array('id' => '706','state_id' => '35','name' => 'Pithoragarh'),
  array('id' => '707','state_id' => '35','name' => 'Bageshwar'),
  array('id' => '708','state_id' => '35','name' => 'Champawat'),
  array('id' => '709','state_id' => '35','name' => 'Nainital'),
  array('id' => '710','state_id' => '36','name' => 'Alipurduar District'),
  array('id' => '711','state_id' => '36','name' => 'Bankura'),
  array('id' => '712','state_id' => '36','name' => 'Basirhat HD (North 24 Parganas)'),
  array('id' => '713','state_id' => '36','name' => 'Birbhum'),
  array('id' => '714','state_id' => '36','name' => 'Bishnupur HD (Bankura)'),
  array('id' => '715','state_id' => '36','name' => 'Cooch Behar'),
  array('id' => '716','state_id' => '36','name' => 'Dakshin Dinajpur'),
  array('id' => '717','state_id' => '36','name' => 'Darjeeling'),
  array('id' => '718','state_id' => '36','name' => 'Diamond Harbor HD (S 24 Parganas)'),
  array('id' => '719','state_id' => '36','name' => 'East Bardhaman'),
  array('id' => '720','state_id' => '36','name' => 'Hoogly'),
  array('id' => '721','state_id' => '36','name' => 'Howrah'),
  array('id' => '722','state_id' => '36','name' => 'Jalpaiguri'),
  array('id' => '723','state_id' => '36','name' => 'Jhargram'),
  array('id' => '724','state_id' => '36','name' => 'Kalimpong'),
  array('id' => '725','state_id' => '36','name' => 'Kolkata'),
  array('id' => '726','state_id' => '36','name' => 'Malda'),
  array('id' => '727','state_id' => '36','name' => 'Murshidabad'),
  array('id' => '728','state_id' => '36','name' => 'Nadia'),
  array('id' => '729','state_id' => '36','name' => 'Nandigram HD (East Medinipore)'),
  array('id' => '730','state_id' => '36','name' => 'North 24 Parganas'),
  array('id' => '731','state_id' => '36','name' => 'Paschim Medinipore'),
  array('id' => '732','state_id' => '36','name' => 'Purba Medinipore'),
  array('id' => '733','state_id' => '36','name' => 'Purulia'),
  array('id' => '734','state_id' => '36','name' => 'Rampurhat HD (Birbhum)'),
  array('id' => '735','state_id' => '36','name' => 'South 24 Parganas'),
  array('id' => '736','state_id' => '36','name' => 'Uttar Dinajpur'),
  array('id' => '737','state_id' => '36','name' => 'West Bardhaman'),
  array('id' => '764','state_id' => '4','name' => 'Hojai'),
  array('id' => '765','state_id' => '4','name' => 'Biswanath'),
  array('id' => '766','state_id' => '4','name' => 'Charaideo'),
  array('id' => '767','state_id' => '4','name' => 'Majuli'),
  array('id' => '768','state_id' => '4','name' => 'South Salmara Mankachar'),
  array('id' => '769','state_id' => '4','name' => 'West Karbi Anglong'),
  array('id' => '770','state_id' => '11','name' => 'Ahmedabad Corporation'),
  array('id' => '771','state_id' => '11','name' => 'Bhavnagar Corporation'),
  array('id' => '772','state_id' => '11','name' => 'Gandhinagar Corporation'),
  array('id' => '773','state_id' => '11','name' => 'Jamnagar Corporation'),
  array('id' => '774','state_id' => '11','name' => 'Junagadh Corporation'),
  array('id' => '775','state_id' => '11','name' => 'Rajkot Corporation'),
  array('id' => '776','state_id' => '11','name' => 'Surat Corporation'),
  array('id' => '777','state_id' => '11','name' => 'Vadodara Corporation'),
  array('id' => '778','state_id' => '31','name' => 'Cheyyar'),
  array('id' => '779','state_id' => '31','name' => 'Aranthangi'),
  array('id' => '780','state_id' => '31','name' => 'Kovilpatti'),
  array('id' => '781','state_id' => '31','name' => 'Ranipet'),
  array('id' => '783','state_id' => '36','name' => 'COOCHBEHAR'),
  array('id' => '796','state_id' => '19','name' => 'Agatti Island')
);