<?php

return array(
    array('id' => '1','name' => 'Andaman and Nicobar Islands'),
    array('id' => '2','name' => 'Andhra Pradesh'),
    array('id' => '3','name' => 'Arunachal Pradesh'),
    array('id' => '4','name' => 'Assam'),
    array('id' => '5','name' => 'Bihar'),
    array('id' => '6','name' => 'Chandigarh'),
    array('id' => '7','name' => 'Chhattisgarh'),
    array('id' => '8','name' => 'Dadra and Nagar Haveli'),
    array('id' => '9','name' => 'Delhi'),
    array('id' => '10','name' => 'Goa'),
    array('id' => '11','name' => 'Gujarat'),
    array('id' => '12','name' => 'Haryana'),
    array('id' => '13','name' => 'Himachal Pradesh'),
    array('id' => '14','name' => 'Jammu and Kashmir'),
    array('id' => '15','name' => 'Jharkhand'),
    array('id' => '16','name' => 'Karnataka'),
    array('id' => '17','name' => 'Kerala'),
    array('id' => '18','name' => 'Ladakh'),
    array('id' => '19','name' => 'Lakshadweep'),
    array('id' => '20','name' => 'Madhya Pradesh'),
    array('id' => '21','name' => 'Maharashtra'),
    array('id' => '22','name' => 'Manipur'),
    array('id' => '23','name' => 'Meghalaya'),
    array('id' => '24','name' => 'Mizoram'),
    array('id' => '25','name' => 'Nagaland'),
    array('id' => '26','name' => 'Odisha'),
    array('id' => '27','name' => 'Puducherry'),
    array('id' => '28','name' => 'Punjab'),
    array('id' => '29','name' => 'Rajasthan'),
    array('id' => '30','name' => 'Sikkim'),
    array('id' => '31','name' => 'Tamil Nadu'),
    array('id' => '32','name' => 'Telangana'),
    array('id' => '33','name' => 'Tripura'),
    array('id' => '34','name' => 'Uttar Pradesh'),
    array('id' => '35','name' => 'Uttarakhand'),
    array('id' => '36','name' => 'West Bengal'),
    array('id' => '37','name' => 'Daman and Diu')
  );